#/etc/init/nefelus-hub.conf
description "Nefelus HUB server"
author      "Giannis Kosmas <kosmas@nefelus.com>"

start on runlevel [2345] 
stop on runlevel [016]

respawn

pre-start script

  #exec >/tmp/error.log 2>&1
  #set -x
  #
  #Remember to disable requiretty flag from sudo config

  exec sudo -u nefelus -i /usr/share/nefelus/hub/startup.sh start 

end script

post-stop script

  exec sudo -u nefelus -i /usr/share/nefelus/hub/startup.sh stop

end script
